-- section 1 table 1
SELECT PLAYERS_DETAIL.FULL_NAME,
       PLAYERS_DETAIL.HEIGHT
FROM PLAYERS_DETAIL
 JOIN AWARDS ON AWARDS.player_id = PLAYERS_DETAIL.player_id
WHERE AWARDS.SEASON IN (2019,2020,2021,2022,2023,2024);

-- section 1 table 2
SELECT FULL_NAME,
       HEIGHT,
       SEASON
FROM PLAYERS_DETAIL
    JOIN TOP_PLAYERS ON TOP_PLAYERS.player_id = PLAYERS_DETAIL.player_id
WHERE TOP_PLAYERS.season IN (2019,2020,2021,2022,2023,2024)
GROUP BY FULL_NAME,HEIGHT, SEASON;
-- -------------------------------------------------------------------------------------------------
-- section 2 table 1
SELECT FULL_NAME, HEIGHT, YEAR_MIN, YEAR AS SEASON
FROM WINNER_TEAMS
JOIN PLAYERS_DETAIL ON WINNER_TEAMS.player_id = PLAYERS_DETAIL.player_id
WHERE WINNER_TEAMS.YEAR IN (2023,2024)
GROUP BY FULL_NAME, HEIGHT, YEAR_MIN, SEASON;

-- section 2 table 2
SELECT FULL_NAME, HEIGHT, YEAR_MIN, TOP_PLAYERS.SEASON
FROM TOP_PLAYERS
JOIN PLAYERS_DETAIL ON TOP_PLAYERS.player_id = PLAYERS_DETAIL.player_id
WHERE TOP_PLAYERS.SEASON IN (2023, 2024) AND
      TOP_PLAYERS.Rk <= 15
GROUP BY FULL_NAME, HEIGHT, YEAR_MIN, TOP_PLAYERS.SEASON;
-- -------------------------------------------------------------------------------------------------
