-- section 1 table 1
SELECT PLAYERS_DETAIL.FULL_NAME,
       PLAYERS_DETAIL.HEIGHT
FROM PLAYERS_DETAIL
 JOIN AWARDS ON AWARDS.player_id = PLAYERS_DETAIL.player_id
WHERE AWARDS.SEASON IN (2019,2020,2021,2022,2023,2024);

-- section 1 table 2
SELECT FULL_NAME,
       HEIGHT,
       SEASON
FROM PLAYERS_DETAIL
    JOIN TOP_PLAYERS ON TOP_PLAYERS.player_id = PLAYERS_DETAIL.player_id
WHERE TOP_PLAYERS.season IN (2019,2020,2021,2022,2023,2024)
GROUP BY FULL_NAME,HEIGHT, SEASON;
-- -------------------------------------------------------------------------------------------------
-- section 2 table 1
select FULL_NAME, HEIGHT, (YEAR - YEAR_MIN) AS EXPERIENCE, YEAR AS SEASON
from WINNER_TEAMS
join PLAYERS_DETAIL on WINNER_TEAMS.player_id = PLAYERS_DETAIL.player_id
where WINNER_TEAMS.YEAR in (2023,2024)
group by FULL_NAME, HEIGHT, (YEAR - YEAR_MIN), YEAR;

-- section 2 table 2
SELECT FULL_NAME, HEIGHT, (SEASON - YEAR_MIN) AS EXPERIENCE, SEASON
FROM TOP_PLAYERS
JOIN PLAYERS_DETAIL ON TOP_PLAYERS.player_id = PLAYERS_DETAIL.player_id
WHERE TOP_PLAYERS.SEASON IN (2023, 2024) AND
      TOP_PLAYERS.Rk <= 15
GROUP BY FULL_NAME, HEIGHT,(SEASON - YEAR_MIN), SEASON;
-- -------------------------------------------------------------------------------------------------
